development:
  adapter: postgresql
  encoding: unicode
  database: ccampbell_development
  pool: 5
  username: charlie
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: ccampbell_test
  pool: 5
  username: charlie
  password:
  timeout: 5000
 